class BackupLog < ApplicationRecord
  enum :backup_type, {
    daily: 0,
    weekly: 1,
    monthly: 2,
    restore: 3
  }

  enum :status, {
    in_progress: 0,
    success: 1,
    failed: 2
  }

  validates :backup_type, presence: true
  validates :status, presence: true
  validates :started_at, presence: true

  scope :recent, -> { order(started_at: :desc) }
  scope :by_type, ->(type) { where(backup_type: type) }
  # Note: .success, .failed, .in_progress scopes are auto-generated by enum

  def duration
    return nil unless completed_at
    completed_at - started_at
  end

  def file_size_mb
    return nil unless file_size
    (file_size.to_f / 1024 / 1024).round(2)
  end
end
